spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # 是否与服务注册于发现组件进行结合
          lower-case-service-id: true # 是将请求路径上的服务名配置为小写(因为服务注册的时候，向注册中心注册时将服务名转成大写的了)
      routes:
        - id: cykb-server
          uri: lb://cykbEsServer
          predicates:
            - Path=/cykb/**
          filters:
            - name: Hystrix # 熔断
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
            - name: Retry # 重试路由器
              args:
                retries: 3
                status: 503
            - name: RequestRateLimiter # 限流
              args:
                key-resolver: "#{@hostAddrKeyResolver}" # 限流的解析器的Bean对象的名字
                redis-rate-limiter.replenishRate: 20 # 令牌通每秒填充平均速率
                redis-rate-limiter.burstCapacity: 100 # 令牌桶的总容量
        - id: uni-id-server
          uri: lb://uniId
          predicates:
            - Path=/uni-id/**
          filters:
            - name: Hystrix # 熔断
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
            - name: Retry # 重试路由器
              args:
                retries: 3
                status: 503
            - name: RequestRateLimiter # 限流
              args:
                key-resolver: "#{@hostAddrKeyResolver}" # 限流的解析器的Bean对象的名字
                redis-rate-limiter.replenishRate: 20 # 令牌通每秒填充平均速率
                redis-rate-limiter.burstCapacity: 100 # 令牌桶的总容量
        - id: baidu-server
          uri: http://www.baidu.com
          predicates:
            - Path=/baidu/**
          filters:
            - StripPrefix=1
  redis:
    host: 192.168.0.110
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.109:7082/eureka/ # 指定注册中心的地址，以便使用服务发现功能
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000 # 熔断的超时时间(毫秒)，默认只有2秒
    
